name: Build system configurations

on:
  pull_request:

jobs:
  build-x86_64-demeter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@latest
      - uses: actions/checkout@v4
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build select system configurations.
        run: |
          # nix flake check --all-systems
          nix build .#nixosConfigurations.demeter.config.system.build.toplevel
  build-aarch64-callisto:
    runs-on: ubuntu-latest-arm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@latest
      - uses: actions/checkout@v4
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build select system configurations.
        run: |
          # nix flake check --all-systems
          nix build .#nixosConfigurations.callisto.config.system.build.toplevel
